server:
  port: 8080

#Service route
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: catalog-service
          uri: lb://catalog-sercie
          predicates:
            - Path=/api/**

        - id: inventroy-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/availability

        - id: blah-blah #was "product-service" I thought it means something
          uri: http://product-service
          predicates:
            - Path=/product-service/**
