server:
  port: 8080

#Service route
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

         -id: catalog-service
         uri: lb://catalog-sercie
        predicates:
          - Path=/api/id/*
          - Path=/api/sku/*

         -id: inventroy-service
          uri: lb://inventory-service
         predicates:
          - Path=/api/availability`