server:
  port: 8090

filter:
  zeros: true

request:
  address:
    sku: http://catalog-service/sku/
    id: http://catalog-service/id/
    availability: http://inventory-service/availability

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
#        ignoreExceptions:
#          - java.lang.RuntimeException
#
#    instances:
#      backendA:
#        baseConfig: default

#      slidingWindowSize: 100
#      permittedNumberOfCallsInHalfOpenState: 30
#      waitDurationInOpenState: 1s
#      failureRateThreshold: 50
#      eventConsumerBufferSize: 10
#      ignoreExceptions:
#        - io.github.robwin.exception.BusinessException